language: node_js
node_js:
  - "8"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g npm@latest
env:
  - TEST_DIR=quality-testing
install:
  - cd $TEST_DIR
  - npm install
#  - npm run start:dev
script:
  - npm run lint
  - npm test