version: '3'
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/database
      - SONARQUBE_JDBC_USERNAME=user
      - SONARQUBE_JDBC_PASSWORD=password
    volumes:
      - ./data/sonarqube/conf:/opt/sonarqube/conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:9000"